services:
  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: fislab_backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=\${DB_PORT}
      - DB_USER=\${DB_USER}
      - DB_PASSWORD=\${DB_PASSWORD}
      - DB_NAME=\${DB_NAME}
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: db
    image: postgres:14.15
    environment:
      POSTGRES_USER: \${DB_USER}
      POSTGRES_PASSWORD: \${DB_PASSWORD}
      POSTGRES_DB: \${DB_NAME}
    ports:
      - "\${DB_PORT}:5433"    # Default ports is 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:
    driver: local

networks:
  app-network:
    driver: bridge